// <auto-generated />
using System;
using CourseLedger.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CourseLedger.Migrations
{
    [DbContext(typeof(StudentrecordContext))]
    [Migration("20260710055201_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EmployeeRole", b =>
                {
                    b.Property<int>("EmployeeId")
                        .HasColumnType("integer")
                        .HasColumnName("Employee_Id");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("Role_Id");

                    b.HasKey("EmployeeId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("Employee_Role", (string)null);
                });

            modelBuilder.Entity("CourseLedger.DataAccess.AcademicRecord", b =>
                {
                    b.Property<string>("StudentId")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("CourseCode")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<int?>("Grade")
                        .HasColumnType("integer");

                    b.HasKey("StudentId", "CourseCode")
                        .HasName("PK__Academic__3D052599C63BA3FB");

                    b.HasIndex("CourseCode");

                    b.ToTable("AcademicRecord", (string)null);
                });

            modelBuilder.Entity("CourseLedger.DataAccess.Course", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Description")
                        .IsUnicode(false)
                        .HasColumnType("text");

                    b.Property<decimal?>("FeeBase")
                        .HasColumnType("decimal(6, 2)");

                    b.Property<int?>("HoursPerWeek")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Code")
                        .HasName("PK__Course__A25C5AA694384533");

                    b.ToTable("Course", (string)null);
                });

            modelBuilder.Entity("CourseLedger.DataAccess.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id")
                        .HasName("PK__Employee__3214EC070CC93D07");

                    b.HasIndex("UserName")
                        .IsUnique()
                        .HasDatabaseName("IX_Employee_UserName");

                    b.ToTable("Employee", (string)null);
                });

            modelBuilder.Entity("CourseLedger.DataAccess.Role", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Role1")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("Role");

                    b.HasKey("Id");

                    b.ToTable("Role", (string)null);
                });

            modelBuilder.Entity("CourseLedger.DataAccess.Student", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id")
                        .HasName("PK__Student__3214EC0749778D6A");

                    b.ToTable("Student", (string)null);
                });

            modelBuilder.Entity("EmployeeRole", b =>
                {
                    b.HasOne("CourseLedger.DataAccess.Employee", null)
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .IsRequired()
                        .HasConstraintName("FK_ToEmployee");

                    b.HasOne("CourseLedger.DataAccess.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .IsRequired()
                        .HasConstraintName("FK_ToRole");
                });

            modelBuilder.Entity("CourseLedger.DataAccess.AcademicRecord", b =>
                {
                    b.HasOne("CourseLedger.DataAccess.Course", "CourseCodeNavigation")
                        .WithMany("AcademicRecords")
                        .HasForeignKey("CourseCode")
                        .IsRequired()
                        .HasConstraintName("FK_AcademicRecord_Course");

                    b.HasOne("CourseLedger.DataAccess.Student", "Student")
                        .WithMany("AcademicRecords")
                        .HasForeignKey("StudentId")
                        .IsRequired()
                        .HasConstraintName("FK_AcademicRecord_Student");

                    b.Navigation("CourseCodeNavigation");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("CourseLedger.DataAccess.Course", b =>
                {
                    b.Navigation("AcademicRecords");
                });

            modelBuilder.Entity("CourseLedger.DataAccess.Student", b =>
                {
                    b.Navigation("AcademicRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
